from sage.matrix.constructor import matrix
from sage.matrix.special import identity_matrix
from sage.matrix.special import block_matrix
from sage.modules.free_module_element import vector
from sage.misc.misc_c import prod
from sage.misc.functional import round


class PseudoMatrix:
    """
    Class representing a pseudo-matrix over a Dedekind domain.
    The pseudo-matrix is the data of `m` ideals `I_m` of the base ring and
    a matrix `M` with `m` rows.

    It represents the module generated by the `I_i r_i`, where
    the `r_i` are the rows of `M`.
    """

    def __init__(self, ideals, matrix, is_phnf=False):
        if not len(ideals) == matrix.nrows():
            raise ValueError("There should be one ideal per row of the matrix.")
        self.__ideals = tuple(ideals)
        self.__matrix = matrix
        self.__base_ring = ideals[0].number_field()
        self.__is_phnf = is_phnf

    def ideals(self):
        return self.__ideals

    def matrix(self):
        return self.__matrix

    def base_ring(self):
        return self.__base_ring

    def steinitz_class_representative(self):
        """
        The steinitz class of the projective module represented
        by ``self`` is the product of the ideal classes of the
        elements of ``self.ideals()``.
        """
        return prod(ideal for ideal in self.pseudo_hermite_form().ideals())

    def pseudo_hermite_form(self):
        r"""
        Return the hermite form of the pseudo-matrix ``(ideals, mat)`` with
        coefficients in a number field and ideals in a maximal order.

        ALGORITHM:

        - Algorithm 1.4.7 from [Coh00]_
        """
        if self.__is_phnf:
            return (
                self,
                identity_matrix(self.matrix().base_ring(), self.matrix().nrows()),
            )
        h = self.matrix().transpose()
        K = h.base_ring()
        k = h.ncols()
        n = h.nrows()
        U = identity_matrix(K, k)
        h_ideals = list(self.ideals())
        j = k - 1
        for i in range(n - 1, -1, -1):
            # Check zero
            if all([h[i, m].is_zero() for m in range(j + 1)]):
                continue
            m = [m for m in range(j + 1) if not h[i, m].is_zero()][-1]
            h[:, m], h[:, j] = h[:, j], h[:, m]
            U[:, m], U[:, j] = U[:, j], U[:, m]
            h_ideals[m], h_ideals[j] = h_ideals[j], h_ideals[m]
            # Put 1 on the main diagonal
            a = ~h[i, j]
            h_ideals[j] *= h[i, j]
            h[:, j] *= a
            U[:, j] *= a
            for m in range(j - 1, -1, -1):
                if h[i, m] == 0:
                    continue
                # Euclidean step
                partial = h[i, m] * h_ideals[m] + h_ideals[j]
                u, v = euclidean_step(h_ideals[m], h_ideals[j], h[i, m], h[i, j])
                U[:, m], U[:, j] = (
                    U[:, m] - h[i, m] * U[:, j],
                    u * U[:, m] + v * U[:, j],
                )
                h[:, m], h[:, j] = (
                    h[:, m] - h[i, m] * h[:, j],
                    u * h[:, m] + v * h[:, j],
                )
                h_ideals[m], h_ideals[j] = (
                    h_ideals[m] * h_ideals[j] * partial**-1,
                    partial,
                )
            # Row reduction step
            for m in range(j + 1, k):
                ideal = ~h_ideals[m] * h_ideals[j]
                q = h[i, m] - _ideal_reduction(ideal, h[i, m])
                # q = h[i, m] - ideal.reduce(h[i, m])
                U[:, m] -= q * U[:, j]
                h[:, m] -= q * h[:, j]
            j -= 1
        first_nonzero = [h[:, j].is_zero() for j in range(k)].index(False)
        h = h[:, first_nonzero:]
        h_ideals = h_ideals[first_nonzero:]
        U = U[:, first_nonzero:]
        return PseudoMatrix(h_ideals, h.transpose(), is_phnf=True), U.transpose()

    def pseudo_basis(self):
        """
        Return a pseudo-basis of the projective module represented
        by ``self``.
        """
        return self.ideals(), self.matrix().rows()

    def integral_basis(self):
        r"""
        Return a `\mathbb{Z}`-basis of the projective module represented
        by self.
        """
        ideals, vecs = self.pseudo_basis()
        return sum(
            [[b * r for b in ideal.basis()] for ideal, r in zip(ideals, vecs)], []
        )

    def lattice_contains(self, elem):
        """
        Checks if ``elem`` lies in the projective module with pseudo-basis ``(ideals, matrix)``
        """
        vec = self.matrix().solve_left(vector(elem))
        return all(c in ideal for c, ideal in zip(vec, self.ideals()))

    def lattice_intersection(self, other):
        """
        Return a pseudo-matrix generating the intersection of the lattice generated by ``self`` and the one generated by ``other``.
        """
        big_matrix = PseudoMatrix(
            self.ideals() + other.ideals(),
            block_matrix(
                [
                    [self.matrix(), self.matrix()],
                    [other.matrix().new_matrix(), other.matrix()],
                ]
            ),
        )
        big_matrix, _ = big_matrix.pseudo_hermite_form()
        m = self.matrix().nrows()
        n = self.matrix().ncols()
        return PseudoMatrix(big_matrix.ideals()[:n], big_matrix.matrix()[:m, :n])


def euclidean_step(ideal_a, ideal_b, a, b):
    r"""
    Let `d = ideal_a a + ideal_b b`. Return `u \in ideal_a d^-1` and
    `v \in ideal_b d^-1` such that au + bv = 1

    ALGORITHM:

    [Coh00]_ Theorem 1.3.3

    EXAMPLES ::

        sage: from vector_bundle.function_field_utility import euclidean_step
        sage: F.<x> = FunctionField(GF(7))
        sage: R.<y> = F[]
        sage: K.<y> = F.extension(y^2 - x^3 - x)
        sage: ideals = [P.prime_ideal() for P in K.places_finite()[:2]]
        sage: a = x^2*y + 3
        sage: b = 2*y*x^5
        sage: d = a*ideals[0] + b*ideals[1]
        sage: u, v = euclidean_step(ideals[0], ideals[1], a, b)
        sage: u in ideals[0] * d^-1
        True
        sage: v in ideals[1] * d^-1
        True
        sage: a*u + b*v
        1
    """
    K = ideal_a.number_field()
    if K(a).is_zero():
        return 0, ~b
    if K(b).is_zero():
        return a ^ -1, 0
    d = a * ideal_a + b * ideal_b
    alpha = a * ideal_a * d**-1
    beta = b * ideal_b * d**-1
    alpha = K.fractional_ideal(alpha.gens())
    s = alpha.element_1_mod(beta)
    u = s / a
    v = (1 - s) / b
    assert u in ideal_a * ~d
    assert v in ideal_b * ~d
    assert a * u + b * v == 1
    return s / a, (1 - s) / b


def _ideal_reduction(ideal, elem):
    """
    Reduce ``elem`` modulo ``ideal``.
    Less precise but more efficient that ``nf_utility.small_lift``.
    """
    basis_matrix = matrix([b.list() for b in ideal.basis()])
    gram_matrix = basis_matrix * basis_matrix.transpose()
    transfo = gram_matrix.LLL_gram().transpose()
    reduced_basis = transfo * basis_matrix
    elem_in_reduced = reduced_basis.solve_left(vector(elem))
    near_element = ideal.number_field()(
        list(
            sum(
                round(e) * r
                for e, r in zip(list(elem_in_reduced), reduced_basis.rows())
            )
        )
    )
    return elem - near_element
