"""(5,5)-isogenies from Jacobians in level-two theta coordinates.

Evaluate the kernel sum of Lubicz--Robert, Fast change of level,
Corollary 4.5, Equation (9), with 5 = 1+1+1+1+1.
"""

from sage.all import vector

from theta_rm.theta import ThetaSurface, normalise, theta_changes


class ThetaFiveIsogeny:
    def __init__(self, A, kernel):
        if A.is_product:
            raise ValueError(
                'This (5,5)-isogeny implementation requires a Jacobian as its domain.'
            )
        self.domain = A
        # If the computed target tuple is zero, change theta structure and recompute.
        for M in theta_changes(A.Fpp):
            self.M = M
            self.source = A if M.is_one() else ThetaSurface(M * vector(A.O))
            O = self._compute(self.source, [M * vector(P) for P in kernel])
            if any(O):
                self.codomain = ThetaSurface(O)
                N = M.inverse()
                self.kernel = tuple(normalise(N * vector(P)) for P in self.kernel)
                return
        raise ValueError(
            'The computed target coordinates are all zero in every theta structure tried.'
        )

    def cycle(self, P, R, S):
        """Return the scaling factor after five additions of R, starting at P.

        S represents P+R. Keep the affine scaling throughout the additions.
        """
        U, V = P, S
        for _ in range(4):
            U, V = V, self.source.diff_add(V, R, U)
        i = next(i for i in range(4) if P[i])
        c = V[i] / P[i]
        assert tuple(V) == tuple(c * t for t in P)
        return c

    def _compute(self, A, kernel):
        P, Q, S = map(normalise, kernel)
        if any(A.mul(5, T) != A.O or T == A.O for T in (P, Q)) or Q in (P, A.mul(2, P)):
            raise ValueError('Supply independent points P, Q of order 5 and S = P+Q.')
        if S not in A.sums(P, Q):
            raise ValueError('S must have the theta coordinates of P+Q or P-Q.')

        # grid[a, b] represents aP+bQ; S fixes the relative signs of P and Q.
        grid = {(a, 0): A.mul(a, P) for a in range(5)}
        grid.update({(0, b): A.mul(b, Q) for b in range(5)})
        grid[1, 1] = S
        for b in range(1, 4):
            grid[1, b + 1] = normalise(A.diff_add(grid[1, b], Q, grid[1, b - 1]))
        for b in range(1, 5):
            for a in range(1, 4):
                grid[a + 1, b] = normalise(A.diff_add(grid[a, b], P, grid[a - 1, b]))
        # The six lines in F_5^2 partition the 24 nonzero kernel points.
        self.generators = (Q, *(grid[1, b] for b in range(5)))
        self.kernel = tuple(dict.fromkeys(grid.values()))
        assert len(self.kernel) == 13  # The origin and 12 pairs {R, -R}.

        # R2 and R3 retain their affine scaling: delta[R] is the fifth power
        # of the scale making R compatible with the null (LR, Definition 3.7).
        self.delta = {}
        for R in self.kernel:
            if R == A.O:
                continue
            R2 = A.double(R)
            R3 = A.diff_add(R2, R, R)
            i = next(i for i in range(4) if R3[i])
            c = R2[i] / R3[i]
            assert tuple(R2) == tuple(c * t for t in R3)
            self.delta[R] = c

        if (
            self.cycle(Q, P, S)
            / self.cycle(P, Q, S)
            * (self.delta[P] / self.delta[Q]) ** 5
            != 1
        ):
            raise ValueError(
                'The subgroup generated by P and Q is not isotropic in A[5].'
            )

        # Sum over the kernel, pairing R and -R (LR, Corollary 4.5).
        O = vector([x**5 for x in A.O])
        for R, c in self.delta.items():
            O += 2 * c * vector([r**5 for r in R])
        return O

    def __call__(self, P):
        P = normalise(P)
        if P in self.kernel:
            return self.codomain.O
        if not self.M.is_one():
            P = normalise(self.M * vector(P))
        total = [p**5 for p in P]
        i = next(i for i in range(4) if P[i])
        for R in self.generators:
            # Either sign of R gives the same sum over <R>.
            S = self.source.sums(P, R)[0]
            translates = [P, S]
            for _ in range(4):
                translates.append(self.source.diff_add(translates[-1], R, translates[-2]))
            c = translates[5][i] / P[i]
            assert tuple(translates[5]) == tuple(c * p for p in P)

            # If delta = lambda_R^5, the fifth-power correction at P+nR is
            # w_n = w_1^n delta^(n(n-1)), with w_1 = 1/(c delta^4).
            delta = self.delta[R]
            w = 1 / (c * delta**4)
            delta2 = delta * delta
            ratio = w * delta2
            for T in translates[1:5]:
                for j in range(4):
                    total[j] += w * T[j]**5
                w *= ratio
                ratio *= delta2
        return normalise(total)
