from sage.all import Matrix

from theta_rm.theta import torsion_label


def splitting_matrix(O, zero_location, i):
    assert i * i == -1
    splitting_map = {
        torsion_label((0, 0), (0, 1)): [
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            -1,
            0,
        ],
        torsion_label((1, 1), (1, 1)): [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
        torsion_label((0, 0), (1, 1)): [
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            -1,
        ],
        torsion_label((0, 1), (1, 0)): [
            1,
            1,
            1,
            1,
            1,
            -1,
            1,
            -1,
            1,
            -1,
            -1,
            1,
            1,
            1,
            -1,
            -1,
        ],
        torsion_label((0, 0), (1, 0)): [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            -1,
            0,
            0,
        ],
        torsion_label((1, 0), (0, 1)): [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
        torsion_label((0, 1), (0, 0)): [
            1,
            1,
            1,
            1,
            1,
            -1,
            1,
            -1,
            1,
            -1,
            -1,
            1,
            -1,
            -1,
            1,
            1,
        ],
        torsion_label((1, 1), (0, 0)): [
            1,
            1,
            1,
            1,
            1,
            -1,
            1,
            -1,
            1,
            1,
            -1,
            -1,
            -1,
            1,
            1,
            -1,
        ],
        torsion_label((1, 0), (0, 0)): [
            1,
            1,
            1,
            1,
            1,
            -1,
            -1,
            1,
            1,
            1,
            -1,
            -1,
            -1,
            1,
            -1,
            1,
        ],
        torsion_label((0, 0), (0, 0)): [
            1,
            i,
            1,
            i,
            1,
            -i,
            -1,
            i,
            1,
            i,
            -1,
            -i,
            -1,
            i,
            -1,
            i,
        ],
    }
    return Matrix(O[0].parent(), 4, splitting_map[zero_location])
